config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create] do
    collection do
      get '/search/' => 'users#search', as: :search
    end
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  constraints Clearance::Constraints::SignedIn.new do
    root to: 'posts#index', as: :signed_in_root
    resources :posts, only: [:index, :create]
    resources :notifications, only: [:index]
    scope '/:username' do
      put '/follow' => 'users#follow', as: :follow_user
      put '/unfollow' => 'users#unfollow', as: :unfollow_user
    end
  end

  scope '/:username' do
    get '/' => 'users#show', as: :user
    resources :posts, only: [:show]
    get '/following' => 'users#following', as: :following
    get '/followers' => 'users#followers', as: :followers
  end

  root to: 'home#index'
end

app/models/concerns/notifiable.rb
module Notifiable
  extend ActiveSupport::Concern

  included do
    mattr_accessor :_notifiers
  end

  def notify(*args)
    _notifiers.each do |notifier|
      notifier.new(self).notify(*args)
    end
  end

  class_methods do
    def notifiers(*notifier_classes)
      self._notifiers = notifier_classes
    end
  end
end

app/models/follower_notification.rb
class FollowerNotification < ActiveRecord::Base
  belongs_to :notification
  belongs_to :follower, class_name: 'User'

  validates_presence_of :follower
end

app/models/followership.rb
class Followership < ActiveRecord::Base
  belongs_to :user
  belongs_to :follower, class_name: 'User'

  validates_presence_of :user, :follower
  validates :follower, uniqueness: { scope: :user }
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  has_one :follower_notification, dependent: :delete

  validates_presence_of :follower_notification, if: :new_follower?
  validates_presence_of :user

  TYPES = {
    new_follower: 0,
    post_liked: 1
  }.freeze

  enum notification_type: TYPES

  scope :unread, ->{ where(read: false) }

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :parent, class_name: 'Post'
  has_many :children, class_name: 'Post', foreign_key: :parent_id

  validates :content,
    presence: true,
    length: { maximum: 160 }

  validates_presence_of :user
  delegate :username, to: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  include Gravtastic
  include Notifiable
  include PgSearch

  notifiers ::ApplicationNotifier
  has_gravatar
  pg_search_scope :search_by_username,
    against: :username,
    using: [:tsearch, :trigram, :dmetaphone],
    ignoring: :accents

  has_many :posts, dependent: :destroy
  has_many :notifications, dependent: :destroy

  has_many :following_relationships,
    class_name: 'Followership',
    foreign_key: :follower_id,
    dependent: :delete_all

  has_many :follower_relationships,
    class_name: 'Followership',
    dependent: :delete_all

  has_many :followers,
    through: :follower_relationships,
    class_name: 'User'

  has_many :following,
    through: :following_relationships,
    class_name: 'User',
    source: :user

  validates :username,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[a-zA-Z0-9_]*\z/ }

  def self.authenticate(email_or_username, password)
    if user = User.find_by(username: email_or_username)
      if password.present? && user.authenticated?(password)
        user
      end
    else
      super(email_or_username, password)
    end
  end

  def follow(user)
    return false if user == self
    unless user.followers.include? self
      user.followers << self
      user.notify(:new_follower, self)
    end
  end

  def following?(user)
    self.following.include? user
  end

  def not_following
    self.class
      .where.not(id: self.following | [self])
  end

  def unread_notifications
    notifications.unread
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  ensure_security_headers # See more: https://github.com/twitter/secureheaders

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'basic'

  def index
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :require_login

  def index
    notifications = fetch_notifications
    notifications.update_all(read: true)
    @notifications = notifications
      .to_a
      .map { |n| NotificationDecorator.new(n) }
  end

  private

  def fetch_notifications
    current_user.notifications
      .includes(follower_notification: :follower)
      .order('read, created_at DESC')
      .limit(50)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:create]

  def index
    @posts = Post
      .includes(:user)
      .where(user_id: current_user.following_ids << current_user.id)
      .order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to posts_path
    else
      redirect_to posts_path,
        notice: 'Something is wrong',
        status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :parent_id)
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :set_user_including_posts, only: [:show]
  before_action :set_user, only: [:followers, :following, :follow, :unfollow]

  def show
  end

  def search
    @users = User.search_by_username(params[:username])
    respond_to do |format|
      format.json { render json: @users.as_json(only: :username) }
      format.html
    end
  end

  def followers
    @users = @user.followers
    render 'index'
  end

  def following
    @users = @user.following
    render 'index'
  end

  def follow
    if current_user.follow(@user)
      redirect_to user_path(@user.username)
    else
      redirect_to(request.referrer || root_path, notice: 'Something went wrong')
    end
  end

  def unfollow
    followership = Followership.find_by!(user_id: @user.id, follower: current_user)
    if followership.destroy
      redirect_to user_path(@user.username)
    else
      redirect_to(request.referrer || root_path, notice: 'Something went wrong')
    end
  end

  private

  def set_user
    @user = User.find_by!(username: params[:username])
  end

  def set_user_including_posts
    @user = User.includes(:posts)
      .find_by(username: params[:username])
  end

  def user_params
    params.require(:user).permit(:email, :password, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar_for(user, size: 100, **options)
    image_tag(user.gravatar_url(size: size), **options)
  end
end

app/views/application/_flash_messages.html.slim
- flash.each do |key, value|
  div id="flash_#{key}" class="flash-#{key}"
    = value

app/views/application/_navigation.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <%= link_to root_path, class: 'logo' do %>
      <%= image_tag "logo_white_small.png", alt: "Logo image" %>
    <% end %>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li class="nav-link">
          <%= link_to 'Home', root_path %>
        </li>
        <% if signed_in? %>
          <li class="nav-link">
            <%= link_to notifications_path do %>
              Notificações
              <% if current_user.unread_notifications.any? %>
                <span class="notifications-count"><%= current_user.unread_notifications.count %></span>
              <% end %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>
    <div class="navigation-tools">
      <div class="search-bar">
        <%= form_tag search_users_path, role: 'search',
          class: 'search-form', method: :get do %>
          <input type="search" placeholder="Buscar usuários" name="username" id="search" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
          </button>
        <% end %>
      </div>
      <nav role="navigation">
        <ul id="js-navigation-menu" class="navigation-menu show">
          <% if signed_in? %>
            <li class="nav-link">
              <%= link_to user_path(current_user.username) do %>
                @<%= current_user.username %>
              <% end %>
            </li>
          <li class="nav-link">
            <%= link_to t('layouts.application.sign_out'), sign_out_path, method: :delete %>
          </li>
        <% else %>
          <li class="nav-link">
            <%= link_to t('layouts.application.sign_in'), sign_in_path %>
          </li>
        <% end %>
      </ul>
    </nav>
    </div>
  </div>
</header>

app/views/application/_people_you_may_know.html.erb
<div class="people-you-may-know">
  <h4>Pessoas que talvez você conheça:</h4>
  <% users.each do |user| %>
    <div class="person-you-may-know">
      <span>
      <%= user_avatar_for(user, size: 50, class: 'profile-image') %>
      </span>
      <span>
      <%= link_to "@#{user.username}", user_path(user.username) %>
      </span>
      <span>
        <%= button_to 'Seguir', follow_user_path(user.username), method: :put %>
      </span>
    </div>
  <% end %>
</div>

app/views/application/_user_info.html.erb
<%= user_avatar_for(user, size: 150, class: 'profile-image') %>
<h2 class="username">@<%= user.username %></h2>
<ul class="stats">
  <li>
    <%= link_to user_path(user.username) do %>
      <span class="stats-caption">
        Posts
      </span>
      <span class="stats-value">
        <%= user.posts.count %>
      </span>
    <% end %>
  </li>

  <li>
    <%= link_to following_path(user.username) do %>
      <span class="stats-caption">
        Seguindo
      </span>
      <span class="stats-value">
        <%= user.following.count %>
      </span>
    <% end %>
  </li>

  <li>
    <%= link_to followers_path(user.username) do %>
      <span class="stats-caption">
        Seguidores
      </span>
      <span class="stats-value">
        <%= user.followers.count %>
      </span>
    <% end %>
  </li>

</ul>
<% if(signed_in? && user != current_user) %>
  <div class="follow-info">
    <% if current_user.following?(user) %>
      <%= button_to 'Seguindo', unfollow_user_path(user.username),
        class: "btn following", method: :put %>
    <% else %>
      <%= button_to 'Seguir', follow_user_path(user.username),
        class: "btn follow", method: :put %>
    <% end %>
  </div>
<% end %>

app/views/home/index.html.erb
<%= content_for :page_title do %>
  Good slogan here
<% end %>
<div class="hero">
	<div class="hero-inner">
    <%= image_tag "logo_white.png", alt: "Logo image" %>
		<div class="hero-copy">
			<h1>Chirrup</h1>
      <p>
        Twitter é overrated.
      </p>	
		</div>
    <%= link_to t('layouts.application.sign_up'), sign_up_path, class: 'btn' %>
    <p><small>Já tem uma conta? <%= link_to 'Entrar', sign_in_path, class: 'sign_in' %></small></p>
	</div>
</div>

app/views/layouts/application.html.slim
doctype 5
html lang="pt"
  head
    meta charset="utf-8"
    meta name="keywords" content=""
    meta name="description" content=""

    title
      = page_title(app_name: 'Chirrup')

    link href="/favicon.ico" rel=("shortcut icon")

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    /![if lt IE 9]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

  body class=body_class
    = render 'navigation'
    = render 'flash_messages'
    div class="wrapper flex-boxes"
      = yield

app/views/layouts/basic.html.slim
doctype 5
html lang="pt"
  head
    meta charset="utf-8"
    meta name="keywords" content=""
    meta name="description" content=""

    title
      = page_title(app_name: 'Chirrup')

    link href="/favicon.ico" rel=("shortcut icon")

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    /![if lt IE 9]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

  body class=body_class
    = render 'flash_messages'
    = yield

app/views/notifications/_new_follower.html.erb
<div class="comment-image">
  <%= user_avatar_for(notification.follower, size: 150) %>
</div>
<div class="comment-content">
  <p><%= t('notifications.messages.new_follower') %>:
    <%= link_to user_path(notification.follower_username) do %>
      @<%= notification.follower_username %>
    <% end %>
  </p>
  <p class="comment-detail">
    <%= time_ago_in_words(notification.created_at) %>
  </p>
</div>

app/views/notifications/_notification.html.erb
<div class="comment notification notification-<%= notification.notification_type %>">
  <%= render partial: notification.notification_type,
    locals: { notification: notification } %>
</div>

app/views/notifications/index.html.erb
<aside class="user-info flex-box flex-box-small">
  <%= render 'user_info', user: current_user %>
</aside>

<div class="content flex-box flex-box-big">
  <section class="notifications">
    <% if @notifications.any? %>
      <%= render partial: 'notification', collection: @notifications %>
    <% else %>
      <h3><%= t('notifications.messages.none') %></h3>
    <% end %>
  </section>
</div>

app/views/posts/_post.html.erb
<div class="comment">
  <div class="comment-image">
    <%= user_avatar_for(post.user, size: 150) %>
  </div>
  <div class="comment-content">
    <h1>
      <%= link_to user_path(post.username) do %>
        @<%= post.username %>
      <% end %>
    </h1>
    <p><%= post.content %></p>
    <p class="comment-detail">
      <%= time_ago_in_words(post.created_at) %>
    </p>
  </div>
</div>

app/views/posts/index.html.erb
<aside class="user-info flex-box flex-box-small">
  <%= render 'user_info', user: current_user %>
</aside>

<div class="content flex-box flex-box-big">
  <section class="new-post">
    <%= form_for(Post.new) do |f| %>
      <%= f.text_area :content,
        placeholder: t(:placeholder, scope: [:posts, :new]),
        class: 'post-editor',
        maxlength: '160',
        required: true
      %>
      <%= f.submit t(:button, scope: [:posts, :new]), id: 'chirp-btn' %>
    <% end %>
  </section>
  <section class="posts">
    <%= render partial: 'post', collection: @posts %>
  </section>
</div>

<% if current_user.not_following.any? %>
  <aside class="flex-box flex-box-small">
    <%= render 'people_you_may_know', users: current_user.not_following.sample(3) %>
  </aside>
<% end %>

app/views/posts/show.html.erb
<aside class="user-info flex-box flex-box-small">
  <%= render 'user_info', user: @post.user %>
</aside>

<div class="content flex-box flex-box-big">
  <section class="posts">
    <%= render partial: 'post', locals: { post: @post } %>
  </section>
</div>

app/views/refills/_comment.html.erb
<div class="comment">
  <div class="comment-image">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo image">
  </div>
  <div class="comment-content">
    <h1>First Comment Title or Author</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, aspernatur, quia modi minima debitis tempora ducimus quam vero impedit alias earum nemo error tenetur sed.</p>
    <p class="comment-detail">Date or details about this post</p>
  </div>
</div>

<div class="comment">
  <div class="comment-image">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_2.png" alt="Logo image">
  </div>
  <div class="comment-content">
    <h1>Another One</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, aspernatur, quia modi minima debitis tempora ducimus quam vero impedit alias earum nemo error tenetur sed.</p>
    <p class="comment-detail">Date or details about this post</p>
  </div>
</div>

app/views/refills/_flashes.html.erb
<div class="flash-success">
  <span>This is a success message <a href="#">with a link</a></span>
</div>

<div class="flash-error">
  <span>This is an error message <a href="#">with a link</a></span>
</div>

<div class="flash-notice">
  <span>This is an notice message <a href="#">with a link</a></span>
</div>

<div class="flash-alert">
  <span>This is an alert message <a href="#">with a link</a></span>
</div>

app/views/refills/_flex_boxes.html.erb
<div class="flex-boxes">
  <a href="javascript:void(0)" class="flex-box flex-box-big">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_2_dark.png" alt="">
    <h1 class="flex-title">A Wide Flex Box Item</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad nostrum, libero! Laborum distinctio necessitatibus voluptates eaque officiis, unde illo, earum voluptatum rerum, reiciendis ipsa ex dolorem a dicta, maxime aliquam.</p>
  </a>
  <a href="javascript:void(0)" class="flex-box">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1_dark.png" alt="">
    <h1 class="flex-title">Flex Box Item</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum molestiae fugiat tenetur fugit atque dignissimos, fugiat natus vitae.</p>
  </a>
  <a href="javascript:void(0)" class="flex-box">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="">
    <h1 class="flex-title">A Flex Box Item</h1>
    <p>Lorem adipisicing elit. Voluptas consectetur tempora quis nam, officia tenetur blanditiis in illo dolor?</p>
  </a>
  <a href="javascript:void(0)" class="flex-box flex-box-big">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_2_dark.png" alt="">
    <h1 class="flex-title">Another Wide Item</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae quis ipsum, officia, aperiam tenetur dolor molestiae voluptate perferendis dolorem vel ex, unde fugit blanditiis sapiente.</p>
  </a>
  <a href="javascript:void(0)" class="flex-box">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_2_dark.png" alt="">
    <h1 class="flex-title">Flex Box Item</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo obcaecati in provident illo.</p>
  </a>
  <a href="javascript:void(0)" class="flex-box">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="">
    <h1 class="flex-title">Last Flex Box Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
</div>

app/views/refills/_hero.html.erb
<div class="hero">
	<div class="hero-inner">
    <a href="" class="hero-logo"><img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png
" alt="Logo Image"></a>
		<div class="hero-copy">
			<h1>Short description of Product</h1>
			<p>A few reasons why this product is worth using, who it's for and why they need it.</p>	
		</div>
    <button>Learn More</button>
	</div>
</div>

app/views/refills/_navigation.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo Image">
    </a>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li class="nav-link"><a href="javascript:void(0)">Products</a></li>
        <li class="nav-link"><a href="javascript:void(0)">About Us</a></li>
        <li class="nav-link"><a href="javascript:void(0)">Contact</a></li>
        <li class="nav-link more"><a href="javascript:void(0)">More</a>
          <ul class="submenu">
            <li><a href="javascript:void(0)">Submenu Item</a></li>
            <li><a href="javascript:void(0)">Another Item</a></li>
            <li class="more"><a href="javascript:void(0)">Item with submenu</a>
              <ul class="submenu">
                <li><a href="javascript:void(0)">Sub-submenu Item</a></li>
                <li><a href="javascript:void(0)">Another Item</a></li>
              </ul>
            </li>
            <li class="more"><a href="javascript:void(0)">Another submenu</a>
              <ul class="submenu">
                <li><a href="javascript:void(0)">Sub-submenu</a></li>
                <li><a href="javascript:void(0)">An Item</a></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <div class="navigation-tools">
      <div class="search-bar">
        <form role="search">
          <input type="search" placeholder="Enter Search" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
          </button>
        </form>
      </div>
      <a href="javascript:void(0)" class="sign-up">Sign Up</a>
    </div>
  </div>
</header>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="text-field">
  <%= form.label t(:username, scope: [:activerecord, :attributes, :user]) %>
  <%= form.text_field :username %>
</div>

<div class="password-field">
  <%= form.label t(:password, scope: [:activerecord, :attributes, :user]) %>
  <%= form.password_field :password %>
</div>

app/views/users/_user.html.erb
<div class="comment">
  <div class="comment-image">
    <%= user_avatar_for(user, size: 100) %>
  </div>
  <div class="comment-content">
    <h1>
      <%= link_to user_path(user.username) do %>
        @<%= user.username %>
      <% end %>
    </h1>
    <p class="comment-detail">
      Membro desde <%= l(user.created_at, format: :short) %>
    </p>
  </div>
</div>

app/views/users/index.html.erb
<aside class="user-info flex-box flex-box-small">
  <%= render 'user_info', user: @user %>
</aside>
<div class="content flex-box flex-box-big">
  <section class="users">
    <%= render partial: 'user', collection: @users %>
  </section>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/search.html.erb
<div class="content flex-box flex-box-big">
  <section class="users">
    <%= render partial: 'user', collection: @users %>
  </section>
</div>

app/views/users/show.html.erb
<aside class="user-info flex-box flex-box-small">
  <%= render 'user_info', user: @user %>
</aside>

<div class="content flex-box flex-box-big">
  <section class="posts">
    <%= render partial: 'posts/post', collection: @user.posts %>
  </section>
</div>